/*
Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do 
not exceed n, find the sum of the even-valued terms.
*/

function Fibonacci(number){

    if(number == 1) return [1];
    else if(number == 2) return [1, 2];

    let fibonnacci = [1, 2];
    let nextValue = 0;
    let counter = 1;

    while(true){

        nextValue = fibonnacci[counter] + fibonnacci[counter - 1];

        if(nextValue <= number)
            fibonnacci.push(nextValue);
        else
            break;

        counter++;
    }

    return fibonnacci;
}

function fiboEvenSum(n) {

    const result = Fibonacci(n).filter(element => element % 2 == 0).reduce((accumulator, currentValue) => accumulator+= currentValue , 0);

    return result;
}


console.log(fiboEvenSum(1000))